name: Pong sbt/sbt
on: repository_dispatch
jobs:
  pong-sbt:
    runs-on: ubuntu-latest
    steps:
    - name: Event Information
      run: |
        echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"
    - name: Generate token
      uses: tibdex/github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}
    - name: PING - Dispatch native script release event
      if: github.event.action != 'pong'
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/rochala/sbt/dispatches \
          -d '{"event_type":"pong","client_payload":{"repository": "rochala/sbtn-dist" }}'
