name: Verify Repositories
on:
  push:
    branches:
      - develop
jobs:
  verify-repositories:
    needs: native-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout rochala/sbtn-dist
      uses: actions/checkout@v3
      with:
        repository: rochala/sbtn-dist
    - name: Test debian artifactory structure
      run: .github/scripts/postMergeTestDebianArtifactory.sh
    - name: Test rpm artifactory structure
      run: .github/scripts/postMergeTestRpmArtifactory.sh
